### ISSUE TITLE
Add a function to load packages, like `tune::load_pkgs()`

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/modelops#2]
The tune package handles [loading package for parallel processing](https://github.com/tidymodels/tune/blob/master/R/load_ns.R), similarly to how we'll need to handle it for model deployment. What is the best option?

- reexport?
- copy the code here?
- do any changes need to be made?

For models that don't use the `required_pkgs` method, this will probably end up being a character vector of package names, I bet.

**Comment by topepo** [comment]
I suggest adding an `attach_packages(character())` function that would fully attach packages (instead of loading their namespace).  

Attaching is, in some ways, safer since some models need to be fully loaded to work. The downside is that there will be naming conflicts (that don't occur when loading the namespace) but I don't think that this is an issue here since there is no script being used to predict. 

We could also check that they are installed but I think that the renv bits would ensure that.

**Comment by juliasilge** [comment]
I'm going to try this:

```r
attach_namespace <- function(pkgs) {
    if (length(pkgs) == 0) {
        return(invisible(TRUE))
    }
    
    loaded <- map_lgl(pkgs, isNamespaceLoaded)
    pkgs <- pkgs[!loaded]
    
    safe_attach <- safely(attachNamespace)
    
    if (length(pkgs) > 0) {
        did_attach <- map(pkgs, safe_attach)
        bad <- compact(map(did_attach, "error"))
        bad <- map_chr(bad, "package")
        if (length(bad) > 1) {
            abort(c("Package(s) could not be attached:", bad))
        }
    }
    
    invisible(TRUE)
}
```

Any suggestions before I start a PR for it?

**Comment by topepo** [comment]
Maybe resetting the random number generator at the end? 

Also, despite my last comment,  should probably have attach package and load namespace functions￼￼￼

**Comment by juliasilge** [comment]
I did make both `load_pkgs()` and `attach_pkgs()`. They work like this:

``` r
library(modelops)

attach_pkgs(c("tidyr", "janeaustenr"))
attach_pkgs(c("tidyr", "bloopy"))
#> Error: Package(s) could not be attached:
#> * bloopy
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
